### ISSUE TITLE
changeset.addError does not seem to work

### ISSUE THREAD

**Issue by matthewvalimaki** [ivanvanderbyl/flood-simple-form#5]
Using latest version of all add-ons and including Ember 2.9.0 and I do not seem to get `changeset.addError()` to work. As in README in the catch() I do exactly the same yet in the template I do not see any of the errors. I tried to track down the reason but did not find anything. I also tried pulling the errors by doing straight up `changeset.errors` in the template but it too had nothing. If I do `console.log(changeset)` right after `changeset.addError()` I do see the new errors.

I also tried `changeset.pushErrors()` as that is what [ember-changeset](https://github.com/DockYard/ember-changeset) uses for the same thing but the result was the same.

**Comment by ivanvanderbyl** [comment]
`pushErrors` was only added a week ago, I haven't update this addon since then.

**Comment by matthewvalimaki** [comment]
@ivanvanderbyl oh sorry for that. I did not understand to check the versions. Thank you for explanation.
