### ISSUE TITLE
validationFormat('email') does not work

### ISSUE THREAD

**Issue by matthewvalimaki** [ivanvanderbyl/flood-simple-form#6]
I tried using `validationFormat('email')` as described in https://github.com/ivanvanderbyl/flood-simple-form/blob/master/tests/dummy/app/controllers/index.js#L14 but the validation did not happen. However using `validateFormat({ type: 'email' })` did work. That is how https://github.com/DockYard/ember-changeset-validations/ documents its email validation.

**Comment by ivanvanderbyl** [comment]
Yep, this needs to be updated, ecv used to accept a string type but doesn't anymore.
